name: StarTickera
description: app hotspot controller
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  rxdart: ^0.27.7
  flutter_bloc: ^8.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.5
  formz: ^0.6.0
  hydrated_bloc: ^9.1.2
  http: ^1.2.0
  eva_icons_flutter: ^3.1.0
  share_plus: ^7.2.1
  path_provider: ^2.1.2
  gap: ^3.0.1
  qr_flutter: ^4.0.0
  badges: ^3.1.2
  aligned_dialog: ^0.0.7
  dropdown_button2: ^2.3.9
  socket_io_client: ^2.0.3+1
  image_picker: ^1.0.7
  connectivity_plus: ^5.0.2
  flutter_launcher_icons: "^0.13.1"
  url_launcher: ^6.2.4
  ftpconnect: ^2.0.5
  permission_handler: ^11.2.0
  network_info_plus: ^4.1.0
  flutter_blue_plus: ^1.31.8
  flutter_esc_pos_utils: ^1.0.0
  location: ^5.0.3
  qr_mobile_vision: ^4.1.4
  pdf: any
  open_file: any
  fl_chart: ^0.66.1
  firebase_core: ^2.24.2
  open_settings_plus: ^0.1.0
  mikrotik_mndp: ^0.0.4
  firebase_database: ^10.4.0
  firebase_auth: ^4.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  test: ^1.24.9

flutter_launcher_icons:
  android: "launcher_icon"
#  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: poppins_bold
      fonts:
        - asset: assets/fontstyles/Poppins/Poppins-Bold.ttf
    - family: poppins_regular
      fonts:
        - asset: assets/fontstyles/Poppins/Poppins-Regular.ttf
    - family: poppins_semi_bold
      fonts:
        - asset: assets/fontstyles/Poppins/Poppins-SemiBold.ttf
    - family: poppins_extra_bold
      fonts:
        - asset: assets/fontstyles/Poppins/Poppins-ExtraBold.ttf

    - family: DDin
      fonts:
        - asset: assets/fontstyles/starlink/D-DIN.otf

    - family: DDin_Bold
      fonts:
        - asset: assets/fontstyles/starlink/D-DIN-Bold.otf
